name: Update README Technologies

on:
  push:
    paths:
      - 'technologies.json'
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update README
        run: |
          chmod +x ./update-readme.sh
          ./update-readme.sh

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README technologies section"
          git push
